language: python
python:
  - "2.7"
install:
  - pip install -r tests-requirements.txt
script:
  py.test --doctest-modules --pep8 -v --cov=bankaccount --cov=myview --cov=utility
after_success:
  codecov
